### ISSUE TITLE
withDelaysIfUnsupported from viewModel

### ISSUE THREAD

**Issue by kgrigsby-codesmith** [johnpatrickmorgan/FlowStacks#17]
Is it possible to use withDelaysIfUnsupported within a view model? I have "@Published var routes: Routes<Screen> = []" defined in my view model. $routes gives me back a publisher and so withDelaysIfUnsupported is not found.

**Comment by johnpatrickmorgan** [comment]
Hi, thanks for raising this. I hadn't considered that use case. It's possible to access `withDelaysIfUnsupported` if you create a Binding from the variable, e.g.:

```swift
Binding(get: { self.routes }, set: { self.routes = $0 })
  .withDelaysIfUnsupported { ... }
```

But it seems like there should be a less awkward way of achieving this.

**Comment by kgrigsby-codesmith** [comment]
Thanks, I did use that Binding trick. Then I ran into the other issue of calculateSteps returning empty when the screens were only different by their associated values.

**Comment by johnpatrickmorgan** [comment]
I've added a slightly friendlier way of achieving this in a view model in `v0.1.6`:
```swift
RouteSteps.withDelaysIfUnsupported(self, \.routes) {
  $0.push(...)
  $0.push(...)
  $0.presentSheet(...)
}
```
