### ISSUE TITLE
How do I animate between root screens.

### ISSUE THREAD

**Issue by kgrigsby-codesmith** [johnpatrickmorgan/FlowStacks#19]
I have an app coordinator that has several child coordinators. I show each child by replacing the root of the app coordinator‘s routes property. Right now it immediately switch between them. Is it possible to dissolve between them?

**Comment by kgrigsby-codesmith** [comment]
I figured it out. I wrapped the assignment of routes with withAnimation.
``` 
       withAnimation {
            routes = [.root(.login(loginCoordinator))]
        }
```

**Comment by johnpatrickmorgan** [comment]
Thanks, glad you figured it out @kgrigsby-codesmith. Incidentally, I'd like to be able to offer some utility methods in this library to swap the top screen for a new one with a custom transition, but in my experimentation, SwiftUI's `.transition(...)` modifier only seems to work for the root screen.
