### ISSUE TITLE
Ambiguous use of popTo when Screen is both Equatable and Identifiable

### ISSUE THREAD

**Issue by chrisballinger** [johnpatrickmorgan/FlowStacks#2]
Really dig what you've got here! Such a beautifully simple approach to programmatic navigation.

Uncovered an issue with the following, possibly common, scenario:

```swift
enum Screen {
    case intro
    case example(Something)
}

extension Screen: Hashable, Identifiable {
    var id: Self { self }
}
```

Adding `Identifiable` conformance to this enum is nice and easy by adding `Hashable` to both the enum and associated value. The issue is that the following public APIs for `popTo(_:)` are now ambiguous:

```swift
extension NFlow where Screen: Equatable {
    public mutating func popTo(_ screen: Screen) -> Bool {
        popTo(where: { $0 == screen })
    }
}

extension NFlow where Screen: Identifiable {
    @discardableResult
    public mutating func popTo(_ screen: Screen) -> Bool {
        popTo(id: screen.id)
    }
}
```

There is an example workaround available below, could submit this as a PR if you'd like.

```swift
extension NFlow where Screen: Identifiable & Equatable {
    /// Avoids an ambiguity for `popTo` when `Screen` is both `Identifiable` and `Equatable`
    @discardableResult
    mutating func popTo(_ screen: Screen) -> Bool {
        popTo(id: screen.id)
    }
}
```

Cheers!

**Comment by johnpatrickmorgan** [comment]
Thanks Chris! And thanks for finding that issue - I like your proposed solution. I'd be very grateful for a PR, but otherwise I'll make your proposed addition later today. Cheers!

**Comment by johnpatrickmorgan** [comment]
Thanks again, your proposed solution has now been added in `v0.0.14`.
