### ISSUE TITLE
.goBack() crashes when called too many times

### ISSUE THREAD

**Issue by romankozak** [johnpatrickmorgan/FlowStacks#26]
On initial screen, first .goBack() doesn't crash, but messes the navigation stack (won't go back from next pushed view).
Second .goBack() crashes due to invalid index

**Comment by DavidKmn** [comment]
This should fix it #29

**Comment by johnpatrickmorgan** [comment]
Thanks @romankozak for raising this issue, and @DavidKmn for the speedy fix! 
Merged and released in [V0.2.1](https://github.com/johnpatrickmorgan/FlowStacks/releases/tag/0.2.1).
