### ISSUE TITLE
Desynchronization of NFlow stack [iOS 15]

### ISSUE THREAD

**Issue by chrisballinger** [johnpatrickmorgan/FlowStacks#3]
I've noticed that occasionally that the NStack stack array gets desynchronized from the application's actual navigation state. This manifests in behavior like: requiring two taps to navigate, navigating to the wrong screen, or double-navigating to a screen. Have you noticed this at all?

It's not consistently reproducible, but it seems to happen most frequently when navigating quickly back and forth between screens. Trying to dig in a bit deeper to figure out if there's any workarounds.

I've mostly been testing using Xcode 13.0 and the iOS 15.0 simulator. I haven't been able to reproduce so far in Xcode 12.5.1 or Xcode 13.0 when using the iOS 14.5 simulator, which is puzzling. Might be a SwiftUI NavigationLink state bug on iOS 15.

**Comment by johnpatrickmorgan** [comment]
Hi Chris,
I've found that to happen when the stack is increased by more than one screen within one update, e.g.:

```swift
stack.append(screen1)
```
In that case, SwiftUI only shows the first pushed screen. That seems to be a limitation of SwiftUI even without using FlowStacks.

**Comment by johnpatrickmorgan** [comment]
Hi Chris,

I've found that to happen when the stack is increased by more than one screen in quick succession, e.g.:

```swift
stack.append(screen1)
stack.append(screen2)
```

In that case, SwiftUI only shows screen1.

I've also found that it can be problematic to push a new screen while a previous push animation is still in-flight, e.g.:

```swift
stack.append(screen1)
DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
  stack.append(screen2)
}
```

In that case, SwiftUI momentarily shows screen2 before popping back to screen1. 

Both cases seem to be a limitation of SwiftUI as far as I can tell, as I'm able to reproduce them even without using FlowStacks, e.g.:

```swift
import SwiftUI

struct CannotPushMoreThanOneView: View {
  
  class ViewModel: ObservableObject {
    
    @Published var isPushing2 = false
    @Published var isPushing3 = false
    @Published var isPushing4 = false
  }
  
  @ObservedObject var vm = ViewModel()
  
  var body: some View {
    print(vm.isPushing2, vm.isPushing3, vm.isPushing4)
    return NavigationView {
      VStack {
        Button("Push 2 and 3", action: {
          vm.isPushing2 = true
          // SwiftUI does not push 3.
          vm.isPushing3 = true
        })
        Button("Push 2 and then 3", action: {
          vm.isPushing2 = true
          // If delay is less than about 0.45, SwiftUI pushes 2 then 3, then pops back to 2.
          DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
            vm.isPushing3 = true
          }
        })
        NavigationLink(
          "Push",
          destination: NavigationLink(
            "Push",
            destination: NavigationLink(
              "Push",
              destination: Text("4"),
              isActive: $vm.isPushing4
            ).navigationTitle("3"),
            isActive: $vm.isPushing3
          ).navigationTitle("2"),
          isActive: $vm.isPushing2
        ).navigationTitle("1")
      }
    }.navigationViewStyle(StackNavigationViewStyle())
  }
}
```

Do you think these issues are what you've experienced?

**Comment by chrisballinger** [comment]
Not quite, we aren't pushing multiple views in quick succession, so far it's just pushing a single screen at a time in response to a user tapping a `Button`. I tried to make a reproducible example roughly demonstrating the issue, but of course it works just fine:


```swift
enum Screen: Equatable, CaseIterable {
    case screen1
    case screen2
    case screen3
    case screen4
    case screen5

    var title: String {
        let index = Self.allCases.firstIndex(of: self) ?? 0
        return "Screen \(index + 1)"
    }
}

final class NavigationCoordinator: ObservableObject {
    @Published var flow = NFlow<Screen>(root: .screen1)

    func pushNext() {
        switch flow.array.last {
        case .screen1:
            flow.push(.screen2)
        case .screen3:
            flow.push(.screen5)
        case .screen4:
            flow.push(.screen5)
        case .screen2, .screen5, .none:
            fatalError("Not supported")
        }
    }
}

struct ContentView: View {
    @StateObject var navigator: NavigationCoordinator = .init()

    var body: some View {
        NavigationView {
            NStack($navigator.flow) { screen in
                DetailScreen(screen: screen)
            }
        }
        .environmentObject(navigator)
    }
}

struct DetailScreen: View {
    @EnvironmentObject var navigator: NavigationCoordinator

    var screen: Screen

    var body: some View {
        VStack(spacing: 20) {
            switch screen {
            case .screen1, .screen3, .screen4:
                Button("Push Next") {
                    navigator.pushNext()
                }
            case .screen2:
                Button("Push \(Screen.screen3.title)") {
                    navigator.flow.push(.screen3)
                }
                Button("Push \(Screen.screen4.title)") {
                    navigator.flow.push(.screen4)
                }
            case .screen5:
                Text("End")
            }
        }
        .navigationTitle(screen.title)
    }
}
```

My hunch was that the "current" screen `flow.array.last` that we're reading in `pushNext` was getting out of sync if I manually navigated too quickly via button presses. But in this trivial example, it works just fine on iOS 15.

Will continue digging to see if I can figure out what's different and triggering the issue.

**Comment by chrisballinger** [comment]
I might be jumping the gun, but I may have uncovered something promising. I noticed that the push issues only seemed to ever happen starting from the 2nd screen, never from the first. The main difference on the 2nd screen is that we had some `Buttons` in a `LazyVStack` that triggered the navigation to the 3rd screen. By switching from a `LazyVStack` to a `VStack` I have much more difficulty reproducing the issue (so far so good!).

I tried also adding a `LazyVStack` to this example but still wasn't able to reproduce it there.

In any case, reading `flow.array.last` and making assumptions about it reflecting the "current" screen is likely not safe (even long after a user has been sitting on that screen).

**Comment by chrisballinger** [comment]
Hmmm nope, it didn't resolve the issue entirely and still affects another screen (that never used LazyVStack). Nothing too unconventional on that screen other than a GeometryReader around a ScrollView, will see if I can figure out what's going on there.

But at the very least navigation from items in a LazyVStack seems to cause at least some of the issues.

**Comment by chrisballinger** [comment]
@johnpatrickmorgan I don't think the original issue has been completely resolved, just a workaround has been identified. Since it doesn't look like it's possible to detect "holding it wrong" from within the library itself, I think it might be worth exploring that a bit in the README and example code, to ensure that end users break the cycle and don't end up with child views observing too much parent state. Otherwise you might end up with people opening up a new issue for this same bug, or think that it's no longer an issue. Still probably a bug in the SwiftUI internals that might get fixed at some point.

The workaround I ended up using was less than ideal to minimize refactoring, but something like this:

```swift
final class NavigationState: ObservableObject {
    @Published var flow = NFlow<Screen>()
}

final class NavigationCoordinator: ObservableObject {
    /// Do NOT mark this as `@Published`. This is to avoid a SwiftUI bug on iOS 15 where
    /// the navigation state gets desynchronized from the actual state of the nav controller
    var state: NavigationState?

    func showExample() {
        state?.flow.push(.example)
    }
}
```

```swift
struct NavigatedView: View {
    @ObservedObject var navigationState: NavigationState

    var body: some View {
        NavigationView {
            NStack($navigationState.flow) { screen in
// some Child Views
```

```swift
public struct ParentView: View {
    @StateObject var navigator: NavigationCoordinator = .init()
    @StateObject var navigationState: NavigationState = .init()

    public var body: some View {
        NavigatedView(navigationState: navigationState)
        .environmentObject(navigator)        
        .onAppear {
            navigator.state = navigationState
        }
    }
}
```

```swift
public struct ChildView: View {
    @EnvironmentObject var navigator: NavigationCoordinator

    public var body: some View {
        Button(action: {
            navigator.showExample()
        }, label: {
            Text("Show Example")
        })
    }
}
```

**Comment by chrisballinger** [comment]
Oh that's a great idea!

**Comment by johnpatrickmorgan** [comment]
Added a warning to the README to avoid screen's observing navigation state.
