### ISSUE TITLE
Handle deeplinks/push-notifications

### ISSUE THREAD

**Issue by jo8558** [johnpatrickmorgan/FlowStacks#38]
I'm already sorry if the question is easy to answer, but I'm not yet familiar with iOS and SwiftUI, but I'm stuck since I do not know how to handle deeplinks or push notifications properly.

My current approaches end up either with nothing was happing or with an error due to: `﻿Accessing State's value outside of being installed on a View. This will result in a constant Binding of the init`. I guess that this is because the function call to trigger the navigation was executed inside the AppDelegate.

It would be awesome if a sample could be provided for how deeplinks/push-notifications can be handled.

**Comment by johnpatrickmorgan** [comment]
Hi @jo8558, thanks for your question. I've added an [example](https://github.com/johnpatrickmorgan/FlowStacks/commit/e4f28ed9de20e1c01302d498b107b4e1bf095cb3) of deeplinking from a URL using `onOpenURL` which is an alternative to using an AppDelegate.
