### ISSUE TITLE
goBackToRoot with dismiss all opened sheets

### ISSUE THREAD

**Issue by ivan-kolesov** [johnpatrickmorgan/FlowStacks#44]
is it possible to dismiss all opened sheets with goBackToRoot after it?
good to have the case for reset app's state to initial.

**Comment by johnpatrickmorgan** [comment]
Hi @ivan-kolesov! If you make the call within a `withDelaysIfUnsupported` closure, it should dismiss all sheets one at a time. Does that help?

**Comment by ivan-kolesov** [comment]
Thanks a lot. Did with
```
RouteSteps.withDelaysIfUnsupported(self, \.routes) {
  $0.dismiss()
  $0.goBackToRoot()
}
```
but when opened more than one sheets, they close one after one and after return to root with animation.
