### ISSUE TITLE
Toolbar button presenting sheet only works once on iOS...

### ISSUE THREAD

**Issue by ConfusedVorlon** [johnpatrickmorgan/FlowStacks#53]
this is a wierd one.
My guess is that it is a swiftUI bug. I'm mostly posting here just so future folks can find my workaround.
(though if a fix is possible - that would be great!)

Very simple setup; 

Home screen embedded in navigation view

Home screen has a navbar button which presents a sheet

Click on the button - the sheet presents. 
Swipe it down, it dismisses (the dismiss callback _is_ called correctly)

Now you can't click on the toolbar button (though it doesn't show as disabled)

My fix is simply to change the id on the home view. That re-draws it and re-enables the toolbar.
Bug doesn't happen on iPad - go figure...

Am I missing something, or a better fix???

```swift
enum Screen {
  case home
  case sheet
}

struct ContentView: View {
    @State var routes: Routes<Screen> = [.root(.home,embedInNavigationView: true)] {
        didSet {
            print("routes: \(routes)")
        }
    }
    
    @State var homeId:UUID = UUID()
    
    var body: some View {
        Router($routes) { screen, _ in
            switch screen {
            case .home:
                Home(showSheet: showSheet)
                //hacky fix
                //uncomment the .id to fix the issue
                //change the id here to re-enable the toolbar after a the sheet is dismissed...
                //    .id(homeId)
            case .sheet:
                Sheet()
            }
        }
    }
    
    func showSheet(){
        routes.presentSheet(.sheet) {
            print("dismiss")
            //hacky fix
            homeId = UUID()
        }
    }
}

```

```swift
struct Home: View {
    var showSheet:()->Void
    
    var body: some View {
        VStack
        {
            Text("Home")
            
            //this button always works
            Button {
                showSheet()
            } label: {
                Text("Show Sheet")
            }

        }
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    //this button only works once (without the id fix)
                    Button {
                        showSheet()
                    } label: {
                        Text("Sheet")
                    }

                }
            }
    }
}
```

```swift
struct Sheet: View {
    var body: some View {
        Text("Sheet")
    }
}
```

**Comment by johnpatrickmorgan** [comment]
Thanks for sharing this @ConfusedVorlon! I just tried to reproduce this using your example code, but failed: everything worked fine without the ID workaround. I tried using Xcode 14.2 on simulator: both on iOS 14.5 and iOS 16.2. Was your setup different?

**Comment by ConfusedVorlon** [comment]
that's wierd.
here's my sample project:
https://www.dropbox.com/s/0m85n40cwbb9n68/SheetFail.zip?dl=0

to be clear - the button in the main view always works. The toolbar button (top right) only works once.

XCode 14.2, iOS 16.2 or 15.5

**Comment by ConfusedVorlon** [comment]
fyi - the incompatibility on MacOS:

- I set things up with my root view being a NavigationSplitView

I thought this would let me present sheets/etc using FlowStacks (which would be really nice)
Unfortunately, once you present, then hide a sheet - the show/hide sidebar button disappears in mac.

I guess I shouldn't be surprised that NavigationSplitView objects to being inside the router as (presumably) you're using NavigationView around it at some level...

**Comment by ViacheslavKorkhonen** [comment]
For iOS: A simple workaround is to add .frame(height: 96) to the Text("Sheet") in the Button
