### ISSUE TITLE
Not able to achieve Translucent background for fullScreenCover or sheet

### ISSUE THREAD

**Issue by Ajay-Jar** [johnpatrickmorgan/FlowStacks#58]
In the below video I am getting grey background color when presenting screen2 but I am expecting translucent color. 
Please Help me
You can find my code below.

[TranslucentBackground.zip](https://github.com/johnpatrickmorgan/FlowStacks/files/12228967/TranslucentBackground.zip)

https://github.com/johnpatrickmorgan/FlowStacks/assets/137762311/2d2d794f-18cd-4811-b962-52540bb432da

**Comment by johnpatrickmorgan** [comment]
HI @Ajay-Jar, thanks for raising this issue. This behaviour is defined by SwiftUI not FlowStacks - you'll see the same behaviour using vanilla navigation.

However, I can point you to a new api in iOS 16. The new ` .presentationDetents` modifier that [you can use to achieve this effect](https://sarunw.com/posts/swiftui-bottom-sheet/), e.g. by adding ` .presentationDetents([.medium])` to `Screen2`.
