### ISSUE TITLE
17 os navigation problems 

### ISSUE THREAD

**Issue by katringht** [johnpatrickmorgan/FlowStacks#60]
onBack() and .push() on 17os sometimes work weird. 
For instance, routes.push(.screen3) from screen2 go back to screen1

**Comment by johnpatrickmorgan** [comment]
Thanks @katringht! I wasn't able to reproduce this issue, but I made a change in version 0.3.5 for #61 that might just improve things. If you're still experiencing the issue, a small reproduction would be greatly appreciated. Thanks!
