### ISSUE TITLE
ios 17.0.3 backToRoot() and goBackTo(index: 0) problems

### ISSUE THREAD

**Issue by ag-kovalevskiy** [johnpatrickmorgan/FlowStacks#61]
on ios 17.0.3 (iphone XS max) when you do backToRoot() or goBackTo(index: 0), then all screens opened via push are closed sequentially one after another.
Expected Behavior: go straight to the root screen.

**Comment by johnpatrickmorgan** [comment]
Thanks @ag-kovalevskiy! I've made a change in version 0.3.5 to address this issue - please let me know if you still see any strange behaviour.
