### ISSUE TITLE
Xcode warning in 0.3.5 version

### ISSUE THREAD

**Issue by ZOlbrys** [johnpatrickmorgan/FlowStacks#62]
[2023-10-25T18:28:09.205Z] ....akcsxqnsztlozognwdzheadarajc/SourcePackages/checkouts/FlowStacks/Sources/FlowStacks/Node.swift:22:9: error: missing return in closure expected to return 'Bool'

My team uses TCACoordinators repo (also authored by you, thank you!!) and that pulls in FlowStacks via:

`.package(url: "https://github.com/johnpatrickmorgan/FlowStacks", from: "0.3.0"),`

so today after 0.3.5 was released we started seeing warnings about the missing return show up.

Is this something that can be resolved?  If not, we're looking into hard coding 0.3.4 since that was the last version that was working well for us, but we wanted to check!

Thank you!!

**Comment by twprzybysz** [comment]
@johnpatrickmorgan

**Comment by igorgcustodio** [comment]
Same here.

**Comment by johnpatrickmorgan** [comment]
Thanks for picking up on this, and apologies for the error. Version 0.3.6 is now available and should fix the issue.
