### ISSUE TITLE
The closed issue (No way to know when a sheet is dismissed #14) resurfaced

### ISSUE THREAD

**Issue by DeanFs** [johnpatrickmorgan/FlowStacks#78]
The issue [No way to know when a sheet is dismissed](https://github.com/johnpatrickmorgan/FlowStacks/issues/14) resurfaced after the this commit: [Rewrites FlowStacks APIs](https://github.com/johnpatrickmorgan/FlowStacks/commit/35cf35ae90e15b9b78de7a2a4041761191754b36).

This issue is not fixed in the latest version.
Will the onDismiss closure be supported again in a future release.
Or is there any other way to achieve the same effect.
Thank you so much for providing such an excellent library!

**Comment by johnpatrickmorgan** [comment]
Hi @DeanFs , thanks for raising this issue. It's possible to detect dismissals by adding an `onChange` modifier, e.g.:

```swift
.onChange(of: routes) { [oldRoutes = routes] newRoutes in
  let dismissedRoutes = oldRoutes.suffix(from: min(oldRoutes.endIndex, newRoutes.endIndex))
  guard !dismissedRoutes.isEmpty else { return }
  print("dismissed:", dismissedRoutes.map { $0.screen })
}
```
  
This has the advantage of working for all forms of navigation, e.g. push/pop navigation too. Does that work for your use case?
