### ISSUE TITLE
The latest update (0.7.1) broke navigation when using UIKIt lifecycle

### ISSUE THREAD

**Issue by lisindima** [johnpatrickmorgan/FlowStacks#81]
If the application uses UIKIt lifecycle (AppDelegate and SceneDelegate) - navigation completely stops working because `@Environment(\.scenePhase) var scenePhase` cannot intercept the state of the scene

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this @lisindima. I suspect I might have to switch to using Notification Center, as on [this branch](https://github.com/johnpatrickmorgan/FlowStacks/compare/bugfix/issue-81), but I just need too check how that behaves on other platforms.

**Comment by lisindima** [comment]
I didn't find any problems with this thread

**Comment by johnpatrickmorgan** [comment]
I've tweaked those changes for all platforms and included it in `v0.8.0`.
